font_family GeistMono Nerd Font Mono
font_size 13

disable_ligatures no
enable_audio_bell no

shell             zsh
shell_integration disabled

cursor_shape block
cursor_blink_interval 0

url_style curly

remember_window_size no
window_padding_width 30

background_opacity            0.80
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0

cursor_trail 200
cursor_trail_decay 0.1 0.4
curosr_trail_start_threshold 2

sync_to_monitor no

#Colors below (Atom)
background            #1a1818
foreground            #c8c8c8
cursor                #fffefe
selection_background  #302b2a
color0                #302b2a
color8                #4d4d47
color1                #a6463d
color9                #aa000c
color2                #577644
color10               #128c20
color3                #9c5f2a
color11               #fc6a20
color4                #485a98
color12               #7898f7
color5                #854551
color13               #fc89a0
color6                #9c814e
color14               #fad384
color7                #c8c8c8
color15               #fffefe
selection_foreground #1a1818